### ISSUE TITLE
Wrong un-kananized text

### ISSUE THREAD

**Issue by rozboris** [lidialiker/kananized-v2#1]
When you kananize text and then switch back to English, some words (syllables) become incorrect:
site → しte → shite (test here: http://stackoverflow.com/questions/12366549/flot-pie-chart-gives-error-in-firebug-uncaught-exception-invalid-dimensions-f)

I assume it would also not work if there are any Japanese characters on the page (i.e. http://en.wikipedia.org/wiki/Katakana#Script)

**Comment by lidialiker** [comment]
That's correct and happens because two distinct spellings 'si' 'shi' both transformed to し. So there is no way to differ them afterwards.

As for already existing Kana letters on page, yes, they will be transformed back to their spellings in english letters.

Backwards translation will probably be disabled after implementation of on-hover spelling hints.

Thanks for feedback!
